### ISSUE TITLE
Add org-capture template to documentation?

### ISSUE THREAD

**Issue by japhir** [lepisma/org-books#10]
Hi! I'm looking into using this right now to manage my reading lists. It would be nice if you had an example capture template, so we can implement it in our normal capture cycle in stead of needing to call a separate function.

Cheers!

**Comment by lepisma** [comment]
Sure, thanks for the idea! Will be doing it sometime this weekend..

**Comment by lepisma** [comment]
Sorry for the extreme delay.

I am not sure whether this fits in nicely since the entries here are not properly templated in the capture sense and also that `org-capture` is basically `org-books-get-details` with better and flexible positioning. Anyway, [here](https://github.com/lepisma/org-books#using-org-capture) is something.
